port : 8088 #监听端口
babelPluginImport : true #是否使用动态加载babel-plugin-import
input_len : 32 #文本框最大字节
inputArea_Num : 300 #文本域最大字节
inputArea_row : 3 #文本域row
param_split_num : 7
status_code : 
  1000 : '初始化模板成功'
  1001 : 'namespace未定义'